 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/look_a_likes", type: :request do
  
  # LookALike. As you add validations to LookALike, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LookALike.create! valid_attributes
      get look_a_likes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      look_a_like = LookALike.create! valid_attributes
      get look_a_like_url(look_a_like)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_look_a_like_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      look_a_like = LookALike.create! valid_attributes
      get edit_look_a_like_url(look_a_like)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LookALike" do
        expect {
          post look_a_likes_url, params: { look_a_like: valid_attributes }
        }.to change(LookALike, :count).by(1)
      end

      it "redirects to the created look_a_like" do
        post look_a_likes_url, params: { look_a_like: valid_attributes }
        expect(response).to redirect_to(look_a_like_url(LookALike.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LookALike" do
        expect {
          post look_a_likes_url, params: { look_a_like: invalid_attributes }
        }.to change(LookALike, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post look_a_likes_url, params: { look_a_like: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested look_a_like" do
        look_a_like = LookALike.create! valid_attributes
        patch look_a_like_url(look_a_like), params: { look_a_like: new_attributes }
        look_a_like.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the look_a_like" do
        look_a_like = LookALike.create! valid_attributes
        patch look_a_like_url(look_a_like), params: { look_a_like: new_attributes }
        look_a_like.reload
        expect(response).to redirect_to(look_a_like_url(look_a_like))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        look_a_like = LookALike.create! valid_attributes
        patch look_a_like_url(look_a_like), params: { look_a_like: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested look_a_like" do
      look_a_like = LookALike.create! valid_attributes
      expect {
        delete look_a_like_url(look_a_like)
      }.to change(LookALike, :count).by(-1)
    end

    it "redirects to the look_a_likes list" do
      look_a_like = LookALike.create! valid_attributes
      delete look_a_like_url(look_a_like)
      expect(response).to redirect_to(look_a_likes_url)
    end
  end
end
